### ISSUE TITLE
Compiling the Chipyard fails

### ISSUE THREAD

**Issue by jordankrim** [CommonEvaluationPlatform/CEP#36]
I am trying to compile the Chipyard (make -f Makefile.chipyard) with the CEP v4.5.  I had successfully done this several weeks ago, but now I am getting an error message:

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at scala.collection.mutable.ResizableArray.ensureSize(ResizableArray.scala:106)
	at scala.collection.mutable.ResizableArray.ensureSize$(ResizableArray.scala:96)
	at scala.collection.mutable.ArrayBuffer.ensureSize(ArrayBuffer.scala:49)
	at scala.collection.mutable.ArrayBuffer.$plus$eq(ArrayBuffer.scala:85)
	at scala.collection.mutable.ArrayBuffer.$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:62)
	at scala.collection.generic.Growable$$Lambda$20/0x000000080116ed60.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.reflect.io.Streamable$Bytes.toByteArray(Streamable.scala:59)
	at scala.reflect.io.Streamable$Bytes.toByteArray$(Streamable.scala:56)
	at scala.reflect.io.Streamable$$anon$1.toByteArray(Streamable.scala:137)
	at scala.reflect.io.Streamable$.bytes(Streamable.scala:137)
	at sbtassembly.MergeStrategy$.$anonfun$deduplicate$3(MergeStrategy.scala:125)
	at sbtassembly.MergeStrategy$$$Lambda$6741/0x0000000801f38b58.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.TraversableLike$$Lambda$40/0x00000008011a3418.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at sbtassembly.MergeStrategy$.$anonfun$deduplicate$1(MergeStrategy.scala:125)
	at sbtassembly.MergeStrategy$$$Lambda$3906/0x00000008019b5798.apply(Unknown Source)
Error during sbt execution: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
make: *** [/mnt/data/projects/avalon/jkrim/avalon-work/Spartan-1/common.mk:200: /mnt/data/projects/avalon/jkrim/avalon-work/Spartan-1/.classpath_cache/chipyard.jar] Error 1

**Comment by bchetwynd** [comment]
Can you clarify what has changed in your environment over the last few weeks?  It seems from the first few errors that there is some array you recently added which is breaking the compilation,

**Comment by jordankrim** [comment]
I am having difficulty determining what I may have changed to initiate this.  I am on a branch so I don't think I have (or can?) update from the head.  Is there any way to chase what got changed and is causing the issue from the messages in the log rather than visa versa?

**Comment by bchetwynd** [comment]
Through git, you can do many things.. some of them bad.    Assuming your internal repository has a github-like interface, you should be able to check your current commit vs the former commit.  I'd recommend working with your colleagues to track that down.

A related question: Did anything about the machine you are working on change?  Package updates by IT?
